version: '2.3'

services:
  nodejs:
    build: ./nodejs
    environment:
      - DATABASE_URL=postgres://eco:dummy@database/eco
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./nodejs/src:/code/src:ro

  rust:
    build: ./rust
    environment:
      - ADDRESS=0.0.0.0:3000
      - DATABASE_URL=postgres://eco:dummy@database/eco
      - RUST_LOG=info
    networks:
      - backend
    ports:
      - 3000:3000

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=eco
      - POSTGRES_PASSWORD=dummy
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - ./database/dataset.sql:/docker-entrypoint-initdb.d/dataset.sql:ro

networks:
  backend: {}
