version: '2.3'

services:
  golang:
    image: jdrouet/eco-backend:golang
    build: ./golang
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3000:8080

  java:
    image: jdrouet/eco-backend:java
    build: ./java
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3001:8080

  nodejs:
    image: jdrouet/eco-backend:nodejs
    build: ./nodejs
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3002:3000

  php:
    image: jdrouet/eco-backend:php
    build: ./php
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - backend
    ports:
      - 3003:80

  python:
    image: jdrouet/eco-backend:python
    build: ./python
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - backend
    ports:
      - 3004:3000

  rust:
    image: jdrouet/eco-backend:rust
    build: ./rust
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    environment:
      - ADDRESS=0.0.0.0:3000
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3005:3000

  blackhole:
    image: ghcr.io/blt/lading:latest
    command: /http_blackhole --config-path /config.toml
    networks:
      - backend
    volumes:
      - ./blackhole/config.toml:/config.toml:ro

  scaphandre:
    image: hubblo/scaphandre
    command: prometheus
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - /proc:/proc
      - /sys/class/powercap:/sys/class/powercap

  prometheus:
    image: prom/prometheus
    command: --config.file /prometheus.yml --log.level=debug
    networks:
      - backend
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config.yml:/prometheus.yml:ro

networks:
  backend: {}
