version: '2.3'

services:
  golang:
    image: jdrouet/eco-backend:golang
    build: ./golang
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3000:8080
    restart: unless-stopped

  java-springboot:
    image: jdrouet/eco-backend:java-springboot
    build: ./java-springboot
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3000:8080
    restart: unless-stopped

  nodejs-express:
    image: jdrouet/eco-backend:nodejs-express
    build: ./nodejs-express
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  php-laravel:
    image: jdrouet/eco-backend:php-laravel
    build: ./php-laravel
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - backend
    ports:
      - 3000:80
    restart: unless-stopped

  python-flask:
    image: jdrouet/eco-backend:python-flask
    build: ./python-flask
    environment:
      - BLACKHOLE_URL=http://blackhole:3000
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  rust-actix:
    image: jdrouet/eco-backend:rust-actix
    build: ./rust-actix
    environment:
      - ADDRESS=0.0.0.0:3000
      - BLACKHOLE_URL=http://blackhole:3000
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  blackhole:
    image: ghcr.io/blt/lading:latest
    command: /http_blackhole --config-path /config.toml
    networks:
      - backend
    volumes:
      - ./blackhole/config.toml:/config.toml:ro

  activity:
    image: jdrouet/docker-activity:canary
    command: file --format csv /data/output.csv
    volumes:
      - ./results:/data
      - /sys/class/powercap:/sys/class/powercap:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend: {}
